version: '2.2'

services:
  es01:
    container_name: es01
    build:
      context: ./
      args:
        - node=es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: "host"