version: '2.2'

services:
  es02:
    container_name: es02
    build:
      context: ./
      args:
        - node=es02
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
     - 9200:9200
     - 9300:9300